apiVersion: v1
kind: ConfigMap
metadata:
  name: phrinifluent-nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      location /static/ {
          alias /usr/share/nginx/html/static;
      }
    }
