apiVersion: v1
kind: ConfigMap
metadata:
  name: phrinifluent-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location /static {
        alias /usr/share/nginx/html/static;
      }
    }
