apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flatchart.fullname" . }}-db-config
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
data:
  POSTGRES_NAME: "postgres"
  POSTGRES_HOST: "{{ include "flatchart.fullname" . }}-db-service"
  POSTGRES_PORT: "5432"
