apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flatchart.fullname" . }}-db-secrets
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.dbSecrets.dbUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.dbSecrets.dbPassword | b64enc | quote }}
