version: '3.8'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/code/staticfiles
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/phrinifluent.crt:/etc/ssl/certs/phrinifluent.crt:ro
      - /etc/ssl/private/phrinifluent.key:/etc/ssl/private/phrinifluent.key:ro
    depends_on:
      - web
    networks:
      - internal

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - internal

# Volumes
volumes:
  postgres_data:
  static_volume:

# Networks
networks:
  internal:
    driver: bridge
