version: '3.8'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_certificate.crt:/etc/ssl/certs/phrinifluent.crt:ro
      - ./ssl_private.key:/etc/ssl/private/phrinifluent.key:ro
    depends_on:
      - web

  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
  static_volume:
