apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: phrinifluent-static-storage
              mountPath: /usr/share/nginx/html/static
      volumes:
        - name: phrinifluent-static-storage
          persistentVolumeClaim:
            claimName: phrinifluent-static-pvc
