apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "flatchart.fullname" . }}-db-pv
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/lib/docker/volumes/phrinifluent-db-pv/_data"
