apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flatchart.fullname" . }}-db-pvc
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dbPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.dbPvc.storageClass | quote }}
