apiVersion: v1
kind: Service
metadata:
  name: {{ include "flatchart.fullname" . }}-db-service
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: phrinifluent-db
    {{- include "flatchart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
