apiVersion: v1
kind: Service
metadata:
  name: {{ include "flatchart.fullname" . }}-static-service
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: nginx
    {{- include "flatchart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
