apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flatchart.fullname" . }}-nginx-config
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
data:
  default.conf: {{ .Values.nginxConfig.defaultConf | toYaml | indent 1 }}
