apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "flatchart.fullname" . }}-static-pv
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/lib/docker/volumes/phrinifluent-static-pv/_data"
