apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flatchart.fullname" . }}-backend-deployment
  labels:
  {{- include "flatchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backendDeployment.replicas }}
  selector:
    matchLabels:
      app: phrinifluent-backend
    {{- include "flatchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: phrinifluent-backend
      {{- include "flatchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: phrinifluent-backend-secrets
        - secretRef:
            name: phrinifluent-db-secrets
        - configMapRef:
            name: {{ include "flatchart.fullname" . }}-backend-config
        - configMapRef:
            name: {{ include "flatchart.fullname" . }}-db-config
        image: {{ .Values.backendDeployment.phrinifluentBackend.image.repository }}:{{
          .Values.backendDeployment.phrinifluentBackend.image.tag | default .Chart.AppVersion
          }}
        name: phrinifluent-backend
        ports:
        - containerPort: 8000
        resources: {}
      initContainers:
      - args: {{- toYaml .Values.backendDeployment.phrinifluentBackendSetup.args | nindent
          8 }}
        command:
        - /bin/sh
        - -c
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: phrinifluent-backend-secrets
        - secretRef:
            name: phrinifluent-db-secrets
        - configMapRef:
            name: {{ include "flatchart.fullname" . }}-backend-config
        - configMapRef:
            name: {{ include "flatchart.fullname" . }}-db-config
        image: {{ .Values.backendDeployment.phrinifluentBackendSetup.image.repository }}:{{
          .Values.backendDeployment.phrinifluentBackendSetup.image.tag | default .Chart.AppVersion
          }}
        name: phrinifluent-backend-setup
        resources: {}
        volumeMounts:
        - mountPath: /app/staticfiles/
          name: phrinifluent-static-storage
      volumes:
      - name: phrinifluent-static-storage
        persistentVolumeClaim:
          claimName: {{ include "flatchart.fullname" . }}-static-pvc
