apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flatchart.fullname" . }}-nginx-config
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location /static {
        alias /usr/share/nginx/html/static;
      }
    }
