apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flatchart.fullname" . }}-tls-secrets
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.tlsSecrets.certFile | b64enc | quote }}
  tls.key: {{ .Files.Get .Values.tlsSecrets.keyFile | b64enc | quote }}
