apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flatchart.fullname" . }}-tls-secrets
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecrets.crt | b64enc | quote }}
  tls.key: {{ .Values.tlsSecrets.key | b64enc | quote }}
