apiVersion: apps/v1
kind: Deployment
metadata:
  name: phrinifluent-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrinifluent-db
  template:
    metadata:
      labels:
        app: phrinifluent-db
    spec:
      containers:
      - name: phrinifluent-db
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
          name: phrinifluent-db-secrets
