apiVersion: v1
kind: PersistentVolume
metadata:
  name: phrinifluent-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/lib/docker/volumes/phrinifluent-db-pv/_data"
