apiVersion: v1
kind: PersistentVolume
metadata:
  name: phrinifluent-static-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/lib/docker/volumes/phrinifluent-static-pv/_data"
