apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phrinifluent-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
