apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flatchart.fullname" . }}-backend-deployment
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backendDeployment.replicas }}
  selector:
    matchLabels:
      app: phrinifluent-backend
      {{- include "flatchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: phrinifluent-backend
        {{- include "flatchart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: phrinifluent-static-storage
          persistentVolumeClaim:
            claimName: {{ include "flatchart.fullname" . }}-static-pvc
      initContainers:
        - name: phrinifluent-backend-setup
          image: {{ .Values.backendDeployment.phrinifluentBackendSetup.image.repository }}:{{ .Values.backendDeployment.phrinifluentBackendSetup.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            {{- toYaml .Values.backendDeployment.phrinifluentBackendSetup.args | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "flatchart.fullname" . }}-backend-secrets
            - secretRef:
                name: {{ include "flatchart.fullname" . }}-db-secrets
            - configMapRef:
                name: {{ include "flatchart.fullname" . }}-backend-config
            - configMapRef:
                name: {{ include "flatchart.fullname" . }}-db-config
          env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          resources: {}
          volumeMounts:
            - mountPath: /app/staticfiles/
              name: phrinifluent-static-storage
      containers:
        - name: phrinifluent-backend
          image: {{ .Values.backendDeployment.phrinifluentBackend.image.repository }}:{{ .Values.backendDeployment.phrinifluentBackend.image.tag }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ include "flatchart.fullname" . }}-backend-secrets
            - secretRef:
                name: {{ include "flatchart.fullname" . }}-db-secrets
            - configMapRef:
                name: {{ include "flatchart.fullname" . }}-backend-config
            - configMapRef:
                name: {{ include "flatchart.fullname" . }}-db-config
          env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          resources: {}
