apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flatchart.fullname" . }}-backend-secrets
  labels:
    {{- include "flatchart.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.backendSecrets.secretKey | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.backendSecrets.adminUsername | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.backendSecrets.adminEmail | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.backendSecrets.adminPassword | b64enc | quote }}
