name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --depth=1 --tags

      - name: Get latest tag or set default
        id: latest_tag
        run: |
          TAG=$(git tag -l --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$TAG" ]; then
            TAG="latest"
          fi
          echo "::set-output name=tag::$TAG"

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      - name: Create Namespace (if not exists)
        run: |
          kubectl get ns phrinifluent || kubectl create ns phrinifluent

      - name: Set up Helm
        uses: azure/setup-helm@v1

      # - name: Add Helm repository
      #   run: helm repo add myrepo https://mychartrepo.com/charts

      # - name: Update Helm repositories
      #   run: helm repo update

      - name: Create and Apply Kubernetes Secrets
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SSL_CERTIFICATE: ${{ secrets.SSL_CERTIFICATE }}
          SSL_KEY: ${{ secrets.SSL_KEY }}
        run: |
          helm upgrade --install ${{ steps.latest_tag.outputs.tag }} ./helm \
            --namespace phrinifluent \
            --set image.tag=${{ steps.latest_tag.outputs.tag }} \
            --set dbSecrets.user=${{ secrets.DB_USER }} \
            --set dbSecrets.password=${{ secrets.DB_PASSWORD }} \
            --set backendSecrets.secretKey=${{ secrets.SECRET_KEY }} \
            --set backendSecrets.adminUsername=${{ secrets.ADMIN_USERNAME }} \
            --set backendSecrets.adminEmail=${{ secrets.ADMIN_EMAIL }} \
            --set backendSecrets.adminPassword=${{ secrets.ADMIN_PASSWORD }} \
            --set-file tlsSecrets.certFile=<(echo "${{ secrets.SSL_CERTIFICATE }}") \
            --set-file tlsSecrets.keyFile=<(echo "${{ secrets.SSL_KEY }}")
